# @path: harst/crate/karst_core/Cargo.toml
# @author: redskaber
# @datetime: 2026-10-01
# @discription:
#  karst_core -- CoreExpr definition (the frozen semantic primitices)

[package]
name = "karst_core"
edition = "2024"
description = "CoreExpr definition (the frozen semantic primitices)"
version.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
karst_span = { path = "../karst_span" }
karst_syntax = { path = "../karst_syntax" }
