# @path: harst/crate/karst_reader/Cargo.toml
# @author: redskaber
# @datetime: 2026-09-30
# @description:
#  karst_reader -- ( Lexer + Parser ) producing spanned SyntaxObjects - Layer 2 crate (span -> syntax -> reader)

[package]
name = "karst_reader"
edition = "2024"
description = "Lexer + Parser producing spanned SyntaxObjects"
version.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
karst_span = { path = "../karst_span" }
karst_syntax = { path = "../karst_syntax" }
